### ISSUE TITLE
Test.read() throws JsonSyntaxException

### ISSUE THREAD

**Issue by Avengess** [loadero/loadero-java#41]
Test endpoints now return a `total_cu_count` field which has not been handled in the Loadero Java client. This renders the Test.read() method unusable. Executable code example:

```java
public static void main( String[] args ) throws IOException
{
    Loadero.init("{access_token}", {project_id});

    Test test = Test.read({test_id});
}
```

Console output:
```
2024-07-29 14:36:12.474 [main] ERROR - tp.CustomResponseHandler.handleResponse(CustomResponseHandler.java:58) - java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 310 path $.total_cu_count - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 310 path $.total_cu_count - https://api.stage.loadero.com/v2/projects/2660205/tests/1572847/
Exception in thread "main" com.loadero.exceptions.ApiException: java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 310 path $.total_cu_count
        at com.loadero.http.CustomResponseHandler.handleResponse(CustomResponseHandler.java:59)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at com.loadero.http.HttpController.request(HttpController.java:37)
        at com.loadero.http.ApiResource.request(ApiResource.java:48)
        at com.loadero.model.Test.read(Test.java:55)
        at QA.App.main(App.java:18)
```

**Comment by Avengess** [comment]
`total_run_count` field handling likely also needs to be implemented

**Comment by Avengess** [comment]
Issue has been fixed in https://github.com/loadero/loadero-java/pull/45.
