### ISSUE TITLE
Test.create() function fails to pass start interval as of Loadero Java v1.1.2

### ISSUE THREAD

**Issue by Avengess** [loadero/loadero-java#42]
Attempting to call the Test.create() function via a TestParams parameter causes `400 Bad Request`, presumably because start interval and participant timeout are not correclty passed in the API request.

Example code to trigger the issue:
```java
  public static void main( String[] args ) throws IOException
  {
      Loadero.init("{access_token}", {project_id});

      TestParams tParams = TestParams
          .builder()
          .withName("Test 1")
          .withMode(TestMode.LOAD)
          .withIncrementStrategy(IncrementStrategy.RANDOM)
          .withStartInterval(Duration.ofSeconds(10))
          .withParticipantTimeout(Duration.ofSeconds(360))
          .withScriptString("testy")
          .build();
          
      Test newTest = Test.create(tParams);
  }
```

Console output:
```
Exception in thread "main" com.loadero.exceptions.ApiException: {
  "code": 400,
  "error": "Unable to process request data: invalid int value provided at \"start_interval\" field"
}
        at com.loadero.http.CustomResponseHandler.handleError(CustomResponseHandler.java:71)
        at com.loadero.http.CustomResponseHandler.handleResponse(CustomResponseHandler.java:50)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at com.loadero.http.HttpController.request(HttpController.java:37)
        at com.loadero.http.ApiResource.request(ApiResource.java:47)
        at com.loadero.model.Test.create(Test.java:79)
        at QA.App.main(App.java:32)
```

I can confirm that this same code succeeds in creating a test in previous releases (except for having to use `withScript()` instead of `withScriptString()` since that method did not exist in some of those releases). This issue with the start interval (and likely participant timeout as well) only got introduced in v1.1.2.

**Comment by paulsgrudups** [comment]
Will be fixed in https://github.com/loadero/loadero-java/pull/44

The issue was that to marshal the time we called `toString` instead of `getSeconds` how it was previously.

**Comment by Avengess** [comment]
`Test.create()` does actually create the test now. There are still issues with the function, however, as the response fails to be processed due to the test resource having a `total_run_count` field (and likely if that were to be resolved, `total_cu_count` would trigger the same issue). I believe that can be resolved in https://github.com/loadero/loadero-java/issues/41, so this particular issue can be considered to be resolved.
